### PR TITLE
Version 2 of User/Organization Account Module

### PR DESCRIPTION
**Pull request by muhammad-ali-e**
## What
- Created a new application with the same V1 methods, with  some changes in the models.
- Implementation of version 2 of the user/organization account module.
- Refactoring to remove django_tenants and replace it with a new context management approach.
- Updated the organization model and related methods for better structure and efficiency.

## Why

- Mandatory changes as part of the multi-tenancy design update.
- To streamline the handling of organization contexts without relying on django_tenants.

## How

- Replaced `tenant_context(organization)` with new `UserContext` methods.
- Updated the `StateStore` to store and manage the organization ID in the current context.
- Refactored the organization model by removing `TenantMixin` and redundant methods.
- Leveraged `OrganizationMixin` for better model structuring.

## Can this PR break any existing features. If yes, please list possible items. If no, please explain why. (PS: Admins do not merge the PR without this section filled)

- The new methods are self-contained ensuring no impact on current functionality.
- Also under feature flag `multi_tenancy_v2`.

## Database Migrations

- 

## Env Config

- 

## Relevant Docs

-

## Related Issues or PRs

1. https://github.com/Zipstack/unstract/pull/422
2. https://github.com/Zipstack/unstract/pull/430

## Dependencies Versions

-

## Notes on Testing

-

## Checklist

I have read and understood the [Contribution Guidelines]().

### CODE REVIEW

**Comment by muhammad-ali-e** [comment]
I see Some sonar issues, 
- Duplication Codes:  
  - The duplicated code is intentional, as we replicated the account application.
- Security hotspot. 
  - The current PR does not introduce any new changes in this area; it only involves copying existing code to the new application.
  - We can mark these security hotspots as acceptable since our application is running behind a proxy.
  - Any necessary changes to this code can be addressed in future updates, as my PR does not modify these functionalities.

**Review by johnyrahul — APPROVED** [review]
LGTM overall. As this is v2 of same account app with changes mentioned in description.
Some of it dependent models will be raised as separate PR as author mentioned

**Comment by athul-rs** [comment]
@muhammad-ali-e One doubt, will we be removing the previous version after the test-runs ? 
Until then are keeping the same duplicates ?

**Comment by muhammad-ali-e** [comment]
> @muhammad-ali-e One doubt, will we be removing the previous version after the test-runs ?
> Until then are keeping the same duplicates ?

@athul-rs  We will only remove the previous version once we have fully transitioned to the new feature and all QA checks are completed. Until then, we will keep all V1 applications, including their tables and schema, to ensure continuity and avoid any disruption.

**Review by athul-rs — APPROVED** [review]
LGTM for the overall code.
Only doubt remains on the duplicate code we are adding to OSS, please proceed if this is alright. cc: @hari-kuriakose

**Review by jagadeeswaran-zipstack — APPROVED** [review]

**Comment by hari-kuriakose** [comment]
Bypassing Sonar duplication issue.

This is because the Django apps are duplicated purposefully, which is the less messier path.  Similarly it's best for the models also to be separate in order to prevent any conflict with prior logic.

**Comment by hari-kuriakose** [comment]
We can take care of duplication when we delete v1 eventually. Bypassing.

**Pull request merged**
