### PR TITLE
[DEPS] SDK patch version bump to 0.31.1

### PR DESCRIPTION
**Pull request by harini-venkataraman**
## What

-

## Why

-

## How

-

## Can this PR break any existing features. If yes, please list possible items. If no, please explain why. (PS: Admins do not merge the PR without this section filled)

-

## Database Migrations

- 

## Env Config

- 

## Relevant Docs

-

## Related Issues or PRs

-

## Dependencies Versions

-

## Notes on Testing

-

## Checklist

I have read and understood the [Contribution Guidelines]().

### CODE REVIEW

**Review by chandrasekharan-zipstack — APPROVED** [review]

**Review by gaya3-zipstack — APPROVED** [review]
Looks good.

**Comment by gaya3-zipstack** [comment]
@harini-venkataraman Pls update public_tools.json here to reflect latest versions. Thought it is not used, It will be used by OSS... @chandrasekharan-zipstack is that right?

**Review by gaya3-zipstack — CHANGES_REQUESTED** [review]
pls update public_tools.json and sample.backend.env also with latest tool build versions

**Comment by harini-venkataraman** [comment]
> pls update public_tools.json and sample.backend.env also with latest tool build versions

@gaya3-zipstack Addressed, thanks for rightly pointing out.

**Comment by gaya3-zipstack** [comment]
@harini-venkataraman pls update backend's sample.env also to reflect latest structure tool version

**Review by gaya3-zipstack — APPROVED** [review]
All is well!

**Pull request merged**
