### PR TITLE
Added README file along with the API Deployment code

### PR DESCRIPTION
**Pull request by muhammad-ali-e**
## What

- Added README file for API Deployemnt

## Why

- Requirements

## How

-

## Can this PR break any existing features. If yes, please list possible items. If no, please explain why. (PS: Admins do not merge the PR without this section filled)

- No

## Database Migrations

- 

## Env Config

- 

## Relevant Docs

-

## Related Issues or PRs

-

## Dependencies Versions

-

## Notes on Testing

-

## Checklist

I have read and understood the [Contribution Guidelines]().

### CODE REVIEW

**Review by vishnuszipstack — APPROVED** [review]

**Review by VikashPratheepan — COMMENTED** [review]
@muhammad-ali-e : We need to include 202 as well right?
If the post call exceeds the timeout, then user needs to get the response in get call.
so we need a 202 here

**Comment by muhammad-ali-e** [comment]
> @muhammad-ali-e : We need to include 202 as well right? If the post call exceeds the timeout, then user needs to get the response in get call. so we need a 202 here

Here We addressed only the documenattion for existing API Deployement beahaviour. No code changes

**Comment by muhammad-ali-e** [comment]
> @muhammad-ali-e, If a API key is provided but in Invalid UUID format, then I am getting 500, have you handled this scenario? We should throw a 400 error also here. Same for GET request If execution_id is provided in invalid UUID format, then I am getting 500 error

@nagesh-zip 
Here We addressed only the documenattion for existing API Deployement beahaviour. No code changes

**Comment by hari-kuriakose** [comment]
@muhammad-ali-e LGTM overall.

However, can we please move this README to `docs/backend/api` in the root level? Let's have all the docs there.

**Comment by ritwik-g** [comment]
@muhammad-ali-e closing this since this is going to be part of the docs repo.

**Pull request closed without merging**
