### PR TITLE
Feat/multi tenancy v2 adapter and connector processor

### PR DESCRIPTION
**Pull request by muhammad-ali-e**
## NOTE

- This PR is intended to make a copy of the existing applications to facilitate the transition to **v2**. It does not aim to change or optimize the existing code.
- Review comments can be added as **TODO** items for future enhancements.

## What

- Introduced v2 changes for the **adapter_processor** and **connector_processor** applications.

## Why

- To align with the updated architecture and ensure compatibility with v2 applications.
- To streamline the handling of organization contexts without relying on django_tenants.

## How

- Updated imports to reference v2 instead of v1 applications.
- Revised the `get_organization` method to utilize the user context.
- Renamed application in `apps.py` of `adapter_processor`.
- Added new `models` with updated table names in adapter_processor with a mixin `DefaultOrganizationMixin`.
- Added `AdapterInstanceModelManager` with `DefaultOrganizationManagerMixin` to get the organization data.

## Can this PR break any existing features. If yes, please list possible items. If no, please explain why. (PS: Admins do not merge the PR without this section filled)

- The new methods are self-contained and changes are under feature flags ensuring no impact on current functionality.

## Database Migrations

- 

## Env Config

- 

## Relevant Docs

-

## Related Issues or PRs

1. https://github.com/Zipstack/unstract/pull/422
2. https://github.com/Zipstack/unstract/pull/430
3. https://github.com/Zipstack/unstract/pull/431
4. https://github.com/Zipstack/unstract/pull/432
5. https://github.com/Zipstack/unstract/pull/447
6. https://github.com/Zipstack/unstract/pull/461
7. https://github.com/Zipstack/unstract/pull/464

## Dependencies Versions

-

## Notes on Testing

-

## Checklist

I have read and understood the [Contribution Guidelines]().

### CODE REVIEW

**Review by hari-kuriakose — APPROVED** [review]
@muhammad-ali-e Models look good.

Ignoring duplication for now. Also all the migration files can be generated later together.

**Review by gaya3-zipstack — COMMENTED** [review]
Don't we need the organization fields for Connector also? Not seeing this in this PR> Is there another PR where this is covered? @muhammad-ali-e

**Review by vishnuszipstack — APPROVED** [review]

**Comment by muhammad-ali-e** [comment]
> Don't we need the organization fields for Connector also? Not seeing this in this PR> Is there another PR where this is covered? @muhammad-ali-e

@gaya3-zipstack Here it is https://github.com/Zipstack/unstract/pull/461

**Review by gaya3-zipstack — APPROVED** [review]
Changes look good.

**Pull request merged**
